name: Build Framework and CLI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: Clean
      run: make clean
    - name: Build
      run: make build
    - name: Install
      run: make install
    - name: Set Up
      run: |
        mockingbird install \
          --project Mockingbird.xcodeproj \
          --target MockingbirdTestsHost \
          --destination MockingbirdTests
    - name: Test
      run: make test
